### ISSUE TITLE
AssertionError: Table lidarseg not found

### ISSUE THREAD

**Issue by acheng1115** [yanx27/2DPASS#10]
Thanks for your great work!
I prepared the data for Nuscenes according to your instructions, and encountered the following problem when training:
![1663916690119](https://user-images.githubusercontent.com/64776148/191908125-e4ae199b-0e8e-403e-a73b-832cf924d349.png)

_Validation sanity check:   0%|                                                                                                                                                                     | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 211, in <module>
    trainer.fit(my_model, train_dataset_loader, val_dataset_loader)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Outdoor/2DPASS/dataloader/dataset.py", line 333, in __getitem__
    data, root = self.point_cloud_dataset[index]
  File "/root/Outdoor/2DPASS/dataloader/pc_dataset.py", line 257, in __getitem__
    pointcloud, sem_label, instance_label, lidar_sample_token = self.loadDataByIndex(index)
  File "/root/Outdoor/2DPASS/dataloader/pc_dataset.py", line 191, in loadDataByIndex
    print(self.nusc.get('lidarseg', lidar_sample_token)['filename'])
  File "/root/miniconda/envs/2dpass/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 214, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found_

**Comment by yanx27** [comment]
Hi @acheng1115 , we ignored `lidarseg` folder in previous README and please download it.
![image](https://user-images.githubusercontent.com/35829331/191928033-a2de3b20-7846-476e-92c1-81eabeef65ab.png)

**Comment by xmuqimingxia** [comment]
I have added 'lidarseg' folder, but above problem still exists.

**Comment by Raiden-cn** [comment]
I solve it due to I update to the newest nuscenes-devkit and download new meta files in nuscenes-lidarseg.

**Comment by shingszelam** [comment]
> I have added 'lidarseg' folder, but above problem still exists.

can you solve it ? i have same problem T - T

**Comment by Raiden-cn** [comment]
@shingszelam ensuring your the version of nus-devkit and nuscenes meta file is a good option.
