### ISSUE TITLE
error while running pretrained model

### ISSUE THREAD

**Issue by bithcc** [yanx27/2DPASS#47]
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    train_dataset_loader, val_dataset_loader, test_dataset_loader = build_loader(configs)
  File "main.py", line 120, in build_loader
    val_pt_dataset = pc_dataset(config, data_path=val_config['data_path'], imageset='val', num_vote=val_config["batch_size"])
  File "/home/ps/hcc/code/2DPASS/dataloader/pc_dataset.py", line 64, in __init__
    calib = self.read_calib(calib_path)
  File "/home/ps/hcc/code/2DPASS/dataloader/pc_dataset.py", line 94, in read_calib
    calib_out['Tr'][:3, :4] = calib_all['Tr'].reshape(3, 4)
KeyError: 'Tr'

**Comment by bithcc** [comment]
solved, redownload the calib.txt in datasets and error fixed
