### ISSUE TITLE
fail to install torchsparse

### ISSUE THREAD

**Issue by bithcc** [yanx27/2DPASS#55]
i could run the code properly before,but after recent upgrade,i have to install torchsparse,but always fail to install it.
error occurs like this:     
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

is there any solution to solve this problem,or does anyone meet the problem same with me?

**Comment by lichonger2** [comment]
Same issues.

**Comment by engineerJPark** [comment]
i've got similar issue like this. i followed the command in the README.md `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0`

```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-it29as2d/setup.py", line 30, in <module>
          setup(
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/pjs_conda/.conda/envs/clip3d/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ```

**Comment by housenz** [comment]
I encountered the same issue, but I found that when connecting remotely via SSH, running the command in the terminal:
pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v1.4.0
results in a timeout. (failed to connect to github.com port 443)
However, without using SSH, the installation completes normally.
